### PR TITLE
Replace HA HTTP_OK by HTTPStatus.OK

### PR DESCRIPTION
**Pull request by McGiverGim**
## Proposed change

The HA project has removed this constant in HA 2021.12.0, as informed in the release notes.

I've tested it and seems to be working.

## Type of change

- [X] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an this integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example entry for `configuration.yaml`:

```yaml
# Example configuration.yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [X] The code has been formatted using Black (`black --fast custom_components`)

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated to README.md

### CODE REVIEW

**Comment by jomavic** [comment]
Checked ok

**Comment by jomavic** [comment]
> This pull request **introduces 1 alert** when merging [fade0a5](https://github.com/Limych/ha-jq300/commit/fade0a5d28d2b86682800c40e7fa9f22ef879d87) into [5301b5c](https://github.com/Limych/ha-jq300/commit/5301b5cb0b5be6648f89b9cec77f41aa3901a985) - [view on LGTM.com](https://lgtm.com/projects/g/Limych/ha-jq300/rev/pr-2d4a34f0f7d23a9554f2bfc3723d6f2e59b9f5a3)
> 
> **new alerts:**
> 
> * 1 for Conflicting attributes in base classes

Checked ok

**Comment by jomavic** [comment]
> This pull request **introduces 1 alert** when merging [fade0a5](https://github.com/Limych/ha-jq300/commit/fade0a5d28d2b86682800c40e7fa9f22ef879d87) into [5301b5c](https://github.com/Limych/ha-jq300/commit/5301b5cb0b5be6648f89b9cec77f41aa3901a985) - [view on LGTM.com](https://lgtm.com/projects/g/Limych/ha-jq300/rev/pr-2d4a34f0f7d23a9554f2bfc3723d6f2e59b9f5a3)
> 
> **new alerts:**
> 
> * 1 for Conflicting attributes in base classes

Checked OK

**Comment by Limych** [comment]
Thanks :heart:

**Pull request merged**
